version: '3.6'

services:
  aspnetapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "3000"
      - "39500"

  mssql:
    environment:
      - SA_PASSWORD=PassWr0d
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"